---
name: Test
on:
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  discussions: write
env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
                    
    steps:
      - uses: actions/checkout@v4
        name: Checkout code
      - name: Install Dependencies
        run: |
          if [[ ${{ matrix.os }} == 'ubuntu-latest' ]]; then
              sudo apt-get update -y;
              sudo apt-get install -y build-essential gcc-multilib;
          elif [[ ${{ matrix.os }} == 'macos-latest' ]]; then
              brew install gcc;
          fi
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target ${{ matrix.target }}
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target ${{ matrix.target }}
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/${{ matrix.target }}/debug/at
  
