---
name: CI
on:
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  discussions: write
env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
                    
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - name: Install Dependencies
        run: |
            case "${{ matrix.os }}" in
            "ubuntu-latest")
              sudo apt-get update -y
              sudo apt-get install -y build-essential gcc-multilib
            ;;
            "macos-latest")
              brew install gcc
            ;;
            *)
              echo "Unsupported OS: ${{ matrix.os }}"
              exit 1
            ;;
            esac
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target ${{ matrix.target }}
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target ${{ matrix.target }}
      # release
      - name: Package
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          tar -czvf at-${{ matrix.target }}.tar.gz target/${{ matrix.target }}/debug/at
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: at-${{ matrix.target }}.tar.gz
  
