---
name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-latest
            rust-version: stable
            target: x86_64-unknown-linux-gnu
            arch: x86_64
          - os: ubuntu-latest
            rust-version: stable
            target: aarch64-unknown-linux-gnu
            arch: aarch64
          - os: macos-latest
            rust-version: stable
            target: x86_64-apple-darwin
            arch: x86_64
          - os: macos-latest
            rust-version: stable
            target: aarch64-apple-darwin
            arch: aarch64
          - os: ubuntu-latest 
            rust-version: beta
            target: x86_64-unknown-linux-gnu
            arch: x86_64
          - os: macos-latest 
            rust-version: beta
            target: x86_64-apple-darwin
            arch: x86_64
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - name: Install Dependencies
        run: |
          if [[ ${{ matrix.os }} == 'ubuntu-latest' ]]; then
              sudo apt-get update -y;
              sudo apt-get install -y build-essential;
              if [[ ${{ matrix.arch }} == 'aarch64' ]]; then
                  sudo apt-get install -y gcc-aarch64-linux-gnu;
              else
                  sudo apt-get install -y gcc-multilib
              fi
          elif [[ ${{ matrix.os }} == 'macos-latest' ]]; then
              brew install gcc;
          fi
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust-version }}
          target: ${{ matrix.target }}
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target ${{ matrix.target }}
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target ${{ matrix.target }}
  
